### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [google/honggfuzz#8]
I would like to point out that identifiers like "[`_FILES_H_`](https://github.com/google/honggfuzz/blob/4f1124fb655c0dab2e18a130199e5f15ab013585/files.h#L24)" and "[`_FUZZ_H_`](https://github.com/google/honggfuzz/blob/3b630b47e7d39e7b36c749290385e284bc5eb950/fuzz.h#L24)" [do not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by robertswiecki** [comment]
Sure, do you wish to create a path, or would you like for project collaborators to do it?

**Comment by robertswiecki** [comment]
Fixed it with https://github.com/google/honggfuzz/commit/876a74cb9c3300543b346da7bf9a965b601af137

**Comment by elfring** [comment]
@robertswiecki: Unfortunately, [this issue](http://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?") was not fixed.

How do you think about to replace the prefix "`_HF`" by "`HONGGFUZZ`"?
